import Head from "next/head";
import Cart from "../components/PopularBooks/Cart";
import Box from "@mui/material/Box";

export default function AddCart() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Box
        sx={{
          maxWidth: "1654px",
          mx: "auto",
        }}
      >
        <Cart />
      </Box>
    </>
  );
}
