import Head from 'next/head';

const Home = () => {
  return (
    <>
      <Head>
        <title>Pathagar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <h2>This is home page</h2>
      </div>
    </>
  )
}

export default Home;